[meta]
title = "随机餐馆"
author = "choco"
version = "1.0"
date = 2024-11-12
update_date = 2024-11-12
desc = "今天吃哪家呢"

# 牌组表
[decks]
"中餐馆" = [
    "弎餐招友所",
    "冯双喜",
    "小民大排档",
    "东北烤肉",
    "山东菜"
]
"西餐馆" = [
    "琳琅",
    "香料厨房",
    "咖喱满满",
    "西提",
    "OAK",
    "土豆泥烤鸡",
    "牛排家"
]
"日料" = [
    "无境",
    "寿司仙人"
]
"韩料" = [
    "姜虎东白丁"
]
"随机餐馆" = [
    "{%中餐馆}",
    "{%西餐馆}",
    "{%日料}",
    "{%韩料}"
]
